name: Keep Alive

on:
  schedule:
    - cron: "0 0 */14 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping blog
        run: curl -s -o /dev/null -w "%{http_code}" https://www.chippanda.top/

      - name: Ping Twikoo
        run: curl -s -o /dev/null -w "%{http_code}" https://twikoo-pied-iota.vercel.app/
